## WORD 2 VEC 

In [23]:
import nltk
import re

In [24]:
from gensim.models import Word2Vec
from nltk.corpus import stopwords

In [25]:
paragraph = """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [26]:
# Cleaning the texts
text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

In [27]:
text

'i have three visions for india. in years of our history, people from all over the world have come and invaded us, captured our lands, conquered our minds. from alexander onwards, the greeks, the turks, the moguls, the portuguese, the british, the french, the dutch, all of them came and looted us, took over what was ours. yet we have not done this to any other nation. we have not conquered anyone. we have not grabbed their land, their culture, their history and tried to enforce our way of life on them. why? because we respect the freedom of others.that is why my first vision is that of freedom. i believe that india got its first vision of this in , when we started the war of independence. it is this freedom that we must protect and nurture and build on. if we are not free, no one will respect us. my second vision for india’s development. for fifty years we have been a developing nation. it is time we see ourselves as a developed nation. we are among the top nations of the world in term

In [28]:
# Preparing the dataset
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]

In [29]:
sentences

[['three', 'visions', 'india', '.'],
 ['years',
  'history',
  ',',
  'people',
  'world',
  'come',
  'invaded',
  'us',
  ',',
  'captured',
  'lands',
  ',',
  'conquered',
  'minds',
  '.'],
 ['alexander',
  'onwards',
  ',',
  'greeks',
  ',',
  'turks',
  ',',
  'moguls',
  ',',
  'portuguese',
  ',',
  'british',
  ',',
  'french',
  ',',
  'dutch',
  ',',
  'came',
  'looted',
  'us',
  ',',
  'took',
  '.'],
 ['yet', 'done', 'nation', '.'],
 ['conquered', 'anyone', '.'],
 ['grabbed',
  'land',
  ',',
  'culture',
  ',',
  'history',
  'tried',
  'enforce',
  'way',
  'life',
  '.'],
 ['?'],
 ['respect', 'freedom', 'others.that', 'first', 'vision', 'freedom', '.'],
 ['believe',
  'india',
  'got',
  'first',
  'vision',
  ',',
  'started',
  'war',
  'independence',
  '.'],
 ['freedom', 'must', 'protect', 'nurture', 'build', '.'],
 ['free', ',', 'one', 'respect', 'us', '.'],
 ['second', 'vision', 'india', '’', 'development', '.'],
 ['fifty', 'years', 'developing', 'nation', '.'

In [49]:
# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1) ## min_count=1 can be changed from 1-10


##size: (default 100) The number of dimensions of the embedding, e.g. the length of the dense vector to represent each token (word).
##window: (default 5) The maximum distance between a target word and words around the target word.
##min_count: (default 5) The minimum count of words to consider when training the model; words with an occurrence less than this count will be ignored.
##workers: (default 3) The number of threads to use while training.
## sg: (default 0 or CBOW) The training algorithm, either CBOW (0) or skip gram (1).

In [53]:
## Build Vocabulary
model.build_vocab(sentences, progress_per=1000)

In [50]:
##words = model.wv.vocab

In [51]:
# Finding Word Vectors of war 
vector = model.wv['war']
vector

array([-0.00218824, -0.00972287,  0.00928283,  0.00200107, -0.00116208,
       -0.00551654, -0.00853069, -0.00989807,  0.00894382, -0.00247945,
        0.0045973 , -0.00449793,  0.00996017,  0.00366728,  0.00104069,
       -0.00405175,  0.00122956, -0.00265283,  0.00733259,  0.00447228,
        0.00100216,  0.00346522,  0.00375648, -0.00682072,  0.00891691,
        0.00172492, -0.00579348,  0.0086576 , -0.00129591,  0.00819227,
       -0.00149608,  0.00698936,  0.00274421, -0.00436402, -0.00374686,
        0.00919505,  0.00156504, -0.00600466,  0.00032883, -0.00196304,
        0.00159142, -0.00770807,  0.00738728,  0.00131375,  0.00788823,
        0.00446025, -0.00438326,  0.00376148, -0.00065541, -0.00984243,
        0.00826438,  0.00964938,  0.00964412, -0.00380826, -0.00845721,
        0.00483684, -0.00766774,  0.00853648,  0.00275693,  0.00558426,
        0.00613284,  0.00045044, -0.00208748,  0.00079128,  0.00985147,
       -0.00710715, -0.0015556 , -0.00234619,  0.00484299,  0.00

In [52]:
# Most similar words
similar = model.wv.most_similar('war')
similar

[('rate', 0.17124967277050018),
 ('’', 0.15878964960575104),
 ('professor', 0.15599356591701508),
 ('material', 0.14556728303432465),
 ('great', 0.14174975454807281),
 ('unless', 0.1397598683834076),
 ('us', 0.1264328509569168),
 ('looted', 0.12486635893583298),
 ('self-reliant', 0.12185988575220108),
 ('third', 0.11057692766189575)]

In [54]:
model.wv.similarity(w1="great", w2="good")

0.038445264

## WORD EMBEDDING

In [26]:
from tensorflow.keras.preprocessing.text import one_hot ## converting sentence to onehot representation given vocabuary size
import numpy as np

In [27]:
sent=['the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [28]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [29]:
###  Vocabulary size  --can be kept any value --this acts as dictionary 
voc_size=10000

One Hot Representation
note -all integers will be less than10000 as wwe have given voc size less than 10000

In [30]:
##One Hot Representation
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[1968, 8064, 4737, 6415], [1968, 8064, 4737, 249], [1968, 5595, 4737, 9836], [3647, 6064, 8545, 1470, 486], [3647, 6064, 8545, 1470, 8931], [4894, 1968, 5752, 4737, 6360], [4835, 7204, 3088, 1470]]


Word Embedding Represntation

In [31]:
## Word Embedding Represntation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences  ## pad_sequence means the size of the sentence should be same
from tensorflow.keras.models import Sequential

## padding='pre' parameter will add 0 in before to make it 8 as we we have defin sent_length to 8
## padding='post' parameter will add 0 in after to make it 8 as we we have defin sent_length to 8

In [32]:
sent_length=8     ## MAX Lenghth is sent_lenght can be changed to 8/10/20/30
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 1968 8064 4737 6415]
 [   0    0    0    0 1968 8064 4737  249]
 [   0    0    0    0 1968 5595 4737 9836]
 [   0    0    0 3647 6064 8545 1470  486]
 [   0    0    0 3647 6064 8545 1470 8931]
 [   0    0    0 4894 1968 5752 4737 6360]
 [   0    0    0    0 4835 7204 3088 1470]]


In [33]:
dim=10

In [34]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [35]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [36]:
print(model.predict(embedded_docs))

[[[-2.28439458e-02  4.98135798e-02 -4.85237502e-02 -3.17731872e-02
   -9.56602022e-03 -1.47382505e-02 -1.75189264e-02 -8.80323350e-04
   -4.89959605e-02  2.96970643e-02]
  [-2.28439458e-02  4.98135798e-02 -4.85237502e-02 -3.17731872e-02
   -9.56602022e-03 -1.47382505e-02 -1.75189264e-02 -8.80323350e-04
   -4.89959605e-02  2.96970643e-02]
  [-2.28439458e-02  4.98135798e-02 -4.85237502e-02 -3.17731872e-02
   -9.56602022e-03 -1.47382505e-02 -1.75189264e-02 -8.80323350e-04
   -4.89959605e-02  2.96970643e-02]
  [-2.28439458e-02  4.98135798e-02 -4.85237502e-02 -3.17731872e-02
   -9.56602022e-03 -1.47382505e-02 -1.75189264e-02 -8.80323350e-04
   -4.89959605e-02  2.96970643e-02]
  [ 2.68990286e-02  4.54950072e-02 -3.41269374e-02 -1.60376206e-02
   -4.16198000e-02 -4.91296053e-02 -1.65725239e-02  4.17890288e-02
    1.83407702e-02  1.71003453e-02]
  [ 3.14444192e-02 -9.55961645e-04 -3.20679769e-02 -2.83207651e-02
    1.12102404e-02 -2.97357924e-02  1.72019936e-02  9.34612751e-03
   -2.67808791e-

In [37]:
embedded_docs[0]

array([   0,    0,    0,    0, 1968, 8064, 4737, 6415])

In [38]:
## 0 has converted into 10 vectors 
print(model.predict(embedded_docs)[0])

[[-0.02284395  0.04981358 -0.04852375 -0.03177319 -0.00956602 -0.01473825
  -0.01751893 -0.00088032 -0.04899596  0.02969706]
 [-0.02284395  0.04981358 -0.04852375 -0.03177319 -0.00956602 -0.01473825
  -0.01751893 -0.00088032 -0.04899596  0.02969706]
 [-0.02284395  0.04981358 -0.04852375 -0.03177319 -0.00956602 -0.01473825
  -0.01751893 -0.00088032 -0.04899596  0.02969706]
 [-0.02284395  0.04981358 -0.04852375 -0.03177319 -0.00956602 -0.01473825
  -0.01751893 -0.00088032 -0.04899596  0.02969706]
 [ 0.02689903  0.04549501 -0.03412694 -0.01603762 -0.0416198  -0.04912961
  -0.01657252  0.04178903  0.01834077  0.01710035]
 [ 0.03144442 -0.00095596 -0.03206798 -0.02832077  0.01121024 -0.02973579
   0.01720199  0.00934613 -0.02678088 -0.03337498]
 [ 0.03339544 -0.04841553 -0.04387951 -0.01038519  0.04802019  0.03712043
   0.0226432  -0.01919406 -0.00470499 -0.0084722 ]
 [-0.03498733 -0.01380736  0.01324196  0.00514722  0.00885059 -0.01531203
  -0.01028433  0.03664862 -0.00473348 -0.04642415]]